cd BatchFiles
call Make_RVP3.bat
cd BatchFiles
call Make_RVP3_Y42.bat
cd BatchFiles
call Make_RVP5.bat
cd BatchFiles
call Make_RVP7.bat
cd BatchFiles
call Make_RVP8.bat
cd BatchFiles
call Make_RVP9.bat
cd BatchFiles
call Make_RVP10.bat
cd BatchFiles
call Make_RVP11.bat
cd BatchFiles
call Make_RVP17.bat
cd BatchFiles
call Make_KBL_uDIMM.bat
cd BatchFiles
call Make_KBL_Refresh.bat