//**********************************************************************
//**********************************************************************
//**                                                                  **
//**        (C)Copyright 1985-2017, American Megatrends, Inc.         **
//**                                                                  **
//**                       All Rights Reserved.                       **
//**                                                                  **
//**      5555 Oakbrook Parkway, Suite 200, Norcross, GA 30093        **
//**                                                                  **
//**                       Phone: (770)-246-8600                      **
//**                                                                  **
//**********************************************************************
//**********************************************************************

/** @file PeriodicSmiControl.c
    Provide functions to install Periodic Smi Control Protocol.  

*/

#include <Token.h>
#include <Library/SmmServicesTableLib.h>
#include <AmiDxeLib.h>
#include <AmiCspLib.h>
#include <PchAccess.h>
#include <Protocol/SmmBase2.h>
#include <Protocol/PeriodicSmiControl.h>

//
// Handle for the Periodic Smi Control Protocol
//
EFI_HANDLE  gHandle = NULL;

// Function declarations

EFI_STATUS
EFIAPI
SbPeriodicSmiControl(
    IN BOOLEAN              Enable,
    IN EFI_HANDLE           DispatchHandle
);

//
// Periodic Smi Control Protocol instance
//
AMI_PERIODICE_SMI_CONTROL_PROTOCOL gPeriodicSmiControl = {
    SbPeriodicSmiControl
};


// Function Definitions

/**
    This function will be called by USBKeyRepeat() function to enable and disable
    SmmPeriodicSmi

    @param  Enable - TRUE: Enable SmmPeriodicSmi / FALSE: Disable SmmPeriodicSmi 
    @param  DispatchHandle - Handle generated by the dispatcher to track the Periodic Smi callback function instance.

    @retval EFI_STATUS

**/
EFI_STATUS
EFIAPI
SbPeriodicSmiControl(
    IN BOOLEAN              Enable,
    IN EFI_HANDLE           DispatchHandle
)
{
    UINT32  SmiEn;
    
    SmiEn = READ_IO32_PM(R_PCH_SMI_EN);
    
    if (Enable == TRUE) {
        //
        // Re-enable Periodic Timer SMI 
        //
        SmiEn |= B_PCH_SMI_EN_SWSMI_TMR;
        WRITE_IO32_PM(R_PCH_SMI_EN, SmiEn);
    } else {
        //
        // Disable Periodic Timer SMI
        //
        SmiEn &= ~(B_PCH_SMI_EN_SWSMI_TMR);
        WRITE_IO32_PM(R_PCH_SMI_EN, SmiEn);
    }
    
    return EFI_SUCCESS;
}

/** @file
    Install Periodic Smi Control Protocol.

    @param ImageHandle - Image handle
    @param SystemTable - Pointer to the system table

    @retval EFI_STATUS
**/
EFI_STATUS
InSmmFunction(
    IN EFI_HANDLE           ImageHandle,
    IN EFI_SYSTEM_TABLE     *SystemTable
)
{
    EFI_STATUS  Status;

    Status = InitAmiSmmLib(ImageHandle, SystemTable);
    
    if (EFI_ERROR(Status)) { 
        return Status;
    }

    //
    // Install the Periodic Smi Control Protocol into the SMM protocol database
    //
    Status = gSmst->SmmInstallProtocolInterface(
                      &gHandle,
                      &gAmiPeriodicSmiControlProtocolGuid,
                      EFI_NATIVE_INTERFACE,
                      &gPeriodicSmiControl
                      );
 
    return Status;
}

/**
    This function for Periodic Smi Control functionality.

    @param ImageHandle Handle for this FFS image
    @param SystemTable Pointer to the system table

    @retval EFI_STATUS
**/
EFI_STATUS
EFIAPI
InitPeriodicSmiControl(
    IN EFI_HANDLE           ImageHandle,
    IN EFI_SYSTEM_TABLE     *SystemTable
)
{
    InitAmiLib(ImageHandle, SystemTable);

    return InitSmmHandler(ImageHandle, SystemTable, InSmmFunction, NULL);
}

//**********************************************************************
//**********************************************************************
//**                                                                  **
//**        (C)Copyright 1985-2017, American Megatrends, Inc.         **
//**                                                                  **
//**                       All Rights Reserved.                       **
//**                                                                  **
//**      5555 Oakbrook Parkway, Suite 200, Norcross, GA 30093        **
//**                                                                  **
//**                       Phone: (770)-246-8600                      **
//**                                                                  **
//**********************************************************************
//**********************************************************************
