/** @file

Copyright (c) 2011, Intel Corporation. All rights reserved.<BR>
This software and associated documentation (if any) is furnished
under a license and may only be used or copied in accordance
with the terms of the license. Except as permitted by such
license, no part of this software or documentation may be
reproduced, stored in a retrieval system, or transmitted in any
form or by any means without the express written consent of
Intel Corporation.

**/

//
// Automatically generated by ACE ver 1.59 PIRQTRANS 
// Please DO NOT modify !!!
//

#define PIRQ_TABLE_IRQ_DATA { \
/*+-------------------+---------------------------+---------------------------+---------------------------+---------------------------+--------------------+*/ \
/*| Device Location   |        Int A Pin          |        Int B Pin          |        Int C Pin          |        Int D Pin          |                    |*/ \
/*+-------------------+---------------------------+---------------------------+---------------------------+---------------------------+--------------------+*/ \
/*| PCI Bus  Dev Num  | Chipset   Bitmap of IRQs  | Chipset   Bitmap of IRQs  | Chipset   Bitmap of IRQs  | Chipset   Bitmap of IRQs  | Physical  Reserved |*/ \
/*| Number   (Shl 3)  | Reg       Routable to Pin | Reg       Routable Pin    | Reg       Routable Pin    | Reg       Routable Pin    | Slot Num  Byte     |*/ \
/*+-------------------+---------------------------+---------------------------+---------------------------+---------------------------+--------------------+*/ \
  { 0x00,    0x08,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,            0,       0 }, /* Device #01h  :Pin0: P.E.G. Root Port D1F0 ( Fn# 002X) :Pin1: P.E.G. Root Port D1F0 ( Fn# 002X) :Pin2: P.E.G. Root Port D1F0 ( Fn# 002X) :Pin3: P.E.G. Root Port D1F0 ( Fn# 002X)*/ \
  { 0x01,    0x00,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,           16,       0 }, /* Slot (Device #0x00) */ \
  { 0x02,    0x00,      0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,           17,       0 }, /* Slot (Device #0x00) */ \
  { 0x03,    0x00,      0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,           0x61,     0xDC78,           18,       0 }, /* Slot (Device #0x00) */ \
  { 0x00,    0x10,      0x60,     0xDC78,           0x00,     0x0000,           0x00,     0x0000,           0x00,     0x0000,            0,       0 }, /* Device #02h  :Pin0: I.G.D. ( Fn# 002X)*/ \
  { 0x00,    0x18,      0x60,     0xDC78,           0x00,     0x0000,           0x00,     0x0000,           0x00,     0x0000,            0,       0 }, /* Device #03h  :Pin0: SA Audio Device ( Fn# 002X)*/ \
  { 0x00,    0x20,      0x60,     0xDC78,           0x00,     0x0000,           0x00,     0x0000,           0x00,     0x0000,            0,       0 }, /* Device #04h  :Pin0: SA Thermal Device ( Fn# 002X)*/ \
  { 0x00,    0x38,      0x60,     0xDC78,           0x00,     0x0000,           0x00,     0x0000,           0x00,     0x0000,            0,       0 }, /* Device #07h  :Pin0: SA Chap Device ( Fn# 002X)*/ \
  { 0x00,    0x98,      0x60,     0xDC78,           0x00,     0x0000,           0x00,     0x0000,           0x00,     0x0000,            0,       0 }, /* Device #13h  :Pin0: Integrated Sensor Hub(ISH) ( Fn# 002X)*/ \
  { 0x00,    0xA0,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,            0,       0 }, /* Device #14h  :Pin0: USB 3.0 xHCI Controller ( Fn# 002X) :Pin1: USB 3.0 xHCI Controller ( Fn# 002X) :Pin2: USB 3.0 xHCI Controller ( Fn# 002X) :Pin3: USB 3.0 xHCI Controller ( Fn# 002X)*/ \
  { 0x00,    0xB0,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,            0,       0 }, /* Device #16h  :Pin0: ME ( Fn# 002X) :Pin1: ME ( Fn# 002X) :Pin2: ME ( Fn# 002X) :Pin3: ME ( Fn# 002X)*/ \
  { 0x00,    0xB8,      0x60,     0xDC78,           0x00,     0x0000,           0x00,     0x0000,           0x00,     0x0000,            0,       0 }, /* Device #17h  :Pin0: SATA Controller ( Fn# 002X)*/ \
  { 0x00,    0xD8,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,            0,       0 }, /* Device #1Bh  :Pin0: PCIE Root Port #17 ( Fn# 002X) :Pin1: PCIE Root Port #17 ( Fn# 002X) :Pin2: PCIE Root Port #17 ( Fn# 002X) :Pin3: PCIE Root Port #17 ( Fn# 002X)*/ \
  { 0x04,    0x00,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x05,    0x00,      0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x06,    0x00,      0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,           0x61,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x07,    0x00,      0x63,     0xDC78,           0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x08,    0x00,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x09,    0x00,      0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x0A,    0x00,      0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,           0x61,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x0B,    0x00,      0x63,     0xDC78,           0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x00,    0xE0,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,            0,       0 }, /* Device #1Ch  :Pin0: PCIE Root Port #1 ( Fn# 002X) :Pin1: PCIE Root Port #1 ( Fn# 002X) :Pin2: PCIE Root Port #1 ( Fn# 002X) :Pin3: PCIE Root Port #1 ( Fn# 002X)*/ \
  { 0x0C,    0x00,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,           33,       0 }, /* Slot (Device #0x00) */ \
  { 0x0D,    0x00,      0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,           34,       0 }, /* Slot (Device #0x00) */ \
  { 0x0E,    0x00,      0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,           0x61,     0xDC78,            8,       0 }, /* Slot (Device #0x00) */ \
  { 0x0F,    0x00,      0x63,     0xDC78,           0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,            9,       0 }, /* Slot (Device #0x00) */ \
  { 0x10,    0x00,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,           10,       0 }, /* Slot (Device #0x00) */ \
  { 0x11,    0x00,      0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,           16,       0 }, /* Slot (Device #0x00) */ \
  { 0x12,    0x00,      0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,           0x61,     0xDC78,           17,       0 }, /* Slot (Device #0x00) */ \
  { 0x13,    0x00,      0x63,     0xDC78,           0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           18,       0 }, /* Slot (Device #0x00) */ \
  { 0x00,    0xE8,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,            0,       0 }, /* Device #1Dh  :Pin0: PCIE Root Port #9 ( Fn# 002X) :Pin1: PCIE Root Port #9 ( Fn# 002X) :Pin2: PCIE Root Port #9 ( Fn# 002X) :Pin3: PCIE Root Port #9 ( Fn# 002X)*/ \
  { 0x14,    0x00,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x15,    0x00,      0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x16,    0x00,      0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,           0x61,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x17,    0x00,      0x63,     0xDC78,           0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x18,    0x00,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x19,    0x00,      0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x1A,    0x00,      0x62,     0xDC78,           0x63,     0xDC78,           0x60,     0xDC78,           0x61,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x1B,    0x00,      0x63,     0xDC78,           0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,            0,       0 }, /* Slot (Device #0x00) */ \
  { 0x00,    0xF8,      0x60,     0xDC78,           0x61,     0xDC78,           0x62,     0xDC78,           0x63,     0xDC78,            0,       0 }, /* Device #1Fh  :Pin0: LPC Bridge ( Fn# 002X) :Pin1: LPC Bridge ( Fn# 002X) :Pin2: LPC Bridge ( Fn# 002X) :Pin3: LPC Bridge ( Fn# 002X)*/ \
}

#define PCI_DEDICATED_IRQS 0xDC78
