/*++
Copyright (c)  2005 - 2007 Intel Corporation. All rights reserved
This software and associated documentation (if any) is furnished
under a license and may only be used or copied in accordance
with the terms of the license. Except as permitted by such
license, no part of this software or documentation may be
reproduced, stored in a retrieval system, or transmitted in any
form or by any means without the express written consent of
Intel Corporation.

Module Name:

  PlatformOptionRomTable_RvpM.h

--*/

//
// Automatically generated by ACE ver 1.59 PIRQTRANS 
// Please DO NOT modify !!!
//


PCI_OPTION_ROM_TABLE mPciOptionRomTable_RvpM[] = { 
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1906,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1913,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1916,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1921,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1926,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x190b,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x191b,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x192b,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x193b,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x192d,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x193d,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x190e,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1915,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x191e,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x190a,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x191a,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x192a,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x193a,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1902,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1912,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1917,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1932,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x191d,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5906,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5913,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5916,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5921,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5926,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5927,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x590b,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x591b,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x592b,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x593b,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x590e,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5915,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x591e,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x590a,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x591a,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x592a,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x593a,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5902,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5912,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5917,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5932,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x591d,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x593d,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1927,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x3e90,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x3e91,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x3e92,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x3e93,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x3e98,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x591c,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x87c0,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x87ca,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    RAID_OPTION_ROM_FILE_GUID,                        // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x17,                                             // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x282a,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    RAID_OPTION_ROM_FILE_GUID,                        // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x17,                                             // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x2822,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    RAID_OPTION_ROM_FILE_GUID,                        // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x17,                                             // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x9d07,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    RAID_OPTION_ROM_FILE_GUID,                        // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x17,                                             // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0xa286,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    RAID_OPTION_ROM_FILE_GUID,                        // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x17,                                             // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0xa28e,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    RAID_OPTION_ROM_FILE_GUID,                        // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x17,                                             // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0xa106,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    RAID_OPTION_ROM_FILE_GUID,                        // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x17,                                             // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0xa107,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    RSTE_OPTION_ROM_FILE_GUID,                        // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x17,                                             // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x2826,                                           // Device ID
  },
  //
  // Option Rom for 
  //
  {
    PXE_OPTION_ROM_FILE_GUID,                         // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x1f,                                             // Device Number
    0x6,                                              // Function Number
    0xffff,                                           // Vendor ID
    0xffff,                                           // Device ID
  },
  //
  // End of OptionRom Entries
  //
  {
    NULL_ROM_FILE_GUID,                               // Guid
    0,                                                // Segment
    0,                                                // Bus Number
    0,                                                // Device Number
    0,                                                // Function Number
    0xffff,                                           // Vendor ID
    0xffff,                                           // Device ID
  }
};

