/*++
Copyright (c)  2005 - 2007 Intel Corporation. All rights reserved
This software and associated documentation (if any) is furnished
under a license and may only be used or copied in accordance
with the terms of the license. Except as permitted by such
license, no part of this software or documentation may be
reproduced, stored in a retrieval system, or transmitted in any
form or by any means without the express written consent of
Intel Corporation.

Module Name:

  PlatformOpRomTable.h

--*/

//
// Automatically generated by ACE ver 1.59 PIRQTRANS 
// Please DO NOT modify !!!
//


//
// Global variables for Option Roms
//
#define NULL_ROM_FILE_GUID \
  { \
    0x00000000, 0x0000, 0x0000, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 \
  }

//
// {6A5F1EF9-C478-42ba-A4DB-C7846CC7DB57}
//
#define MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID \
  { \
    0x6A5F1EF9, 0xC478, 0x42ba, 0xA4, 0xDB, 0xC7, 0x84, 0x6C, 0xC7, 0xDB, 0x57 \
  }

//
// {2BB1381D-AE4F-4b37-B999-812F93811282}
//
#define RAID_OPTION_ROM_FILE_GUID \
  { \
    0x2BB1381D, 0xAE4F, 0x4b37, 0xB9, 0x99, 0x81, 0x2F, 0x93, 0x81, 0x12, 0x82 \
  }

//
// {BF3CE2C0-FCEE-11E1-A21F-0800200C9A66}
//
#define RSTE_OPTION_ROM_FILE_GUID \
  { \
    0xBF3CE2C0, 0xFCEE, 0x11E1, 0xA2, 0x1F, 0x08, 0x00, 0x20, 0x0C, 0x9A, 0x66 \
  }

//
// {58531F11-5C10-4dea-A54C-0A017FA03425}
//
#define PXE_OPTION_ROM_FILE_GUID \
  { \
    0x58531F11, 0x5C10, 0x4dea, 0xA5, 0x4C, 0x0A, 0x01, 0x7F, 0xA0, 0x34, 0x25 \
  }

#define  MAX_ROM_NUMBER      4
